apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-backups
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/file-demo-backups
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

